<div class="section price-guides">
    <div class="title">Price and Specification Guides</div>
    <div class="content">
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/List Price Guide/2021 JSI ATL_CHI_FR Price Guide.pdf') ?>" download>2021 JSI ATL_CHI_FR Price Guide</a></div>
        </div>
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/List Price Guide/2021 JSI Denver Price Guide.pdf') ?>" download>2021 JSI Denver Price Guide</a></div>
        </div>
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/List Price Guide/JSI 2021 ADA Price Guide.pdf') ?>" download>JSI 2021 ADA Price Guide</a></div>
        </div>
    </div>
</div>


<div class="section brochures">
    <div class="title">Brochures</div>
    <div class="content">
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/Brochures/JSI ATL_FR_CHI Designer Kitchen Brochure 2021.pdf') ?>" download>JSI ATL_FR_CHI Designer Kitchen Brochure 2021</a></div>
        </div>
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/Brochures/JSI ATL_FR_CHI Designer Vanity Brochure 2021.pdf') ?>" download>JSI ATL_FR_CHI Designer Vanity Brochure 2021</a></div>
        </div>
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/Brochures/JSI ATL_FR_CHI Premier Kitchen Brochure 2021.pdf') ?>" download>JSI ATL_FR_CHI Premier Kitchen Brochure 2021</a></div>
        </div>
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/Brochures/JSI Denver Designer and Premier Brochure-LowRes.pdf') ?>" download>JSI Denver Designer and Premier Brochure-LowRes</a></div>
        </div>
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/Brochures/JSI Storage Brochure 2021.pdf') ?>" download>JSI Storage Brochure 2021</a></div>
        </div>
        <div class="pdf-item">
            <div class="pdf-name"><a target="_blank" href="<?= $block->getViewFileUrl('images/Brochures/JSI_DoorDisplayerFlyer_2021.pdf') ?>" download>JSI_DoorDisplayerFlyer_2021</a></div>
        </div>
    </div>
</div>

<div class="section promotions">
    <div class="title">News</div>
    <div class="content">
    </div>
</div>

<div class="section news">
    <div class="content images">
        <div class="image-item">
            <img src="<?= $block->getViewFileUrl('images/News/5-PC DRAWERS GRAPHIC.png') ?>" />
        </div>
        <div class="image-item">
            <img src="<?= $block->getViewFileUrl('images/News/Floating Shelves Graphic.png') ?>" />
        </div>
    </div>
</div>
