<div class="account-links">
	<div class="account-link">
		<a href="/customaccount/dashboard/index"><?= __('Dashboard') ?></a>
	</div>
	<div class="account-link">
		<a href="/customaccount/quote/index"><?= __('Quotes') ?></a>
	</div>
	<div class="account-link">
		<a href="/customaccount/order/index"><?= __('Orders') ?></a>
	</div>
	<div class="account-link">
		<a href="/customaccount/replace/index"><?= __('Replacements') ?></a>
	</div>
	<div class="account-link">
		<a href="/customaccount/invoice/index"><?= __('Accounting') ?></a>
	</div>
	<div class="account-link">
		<a href="/customaccount/account/index"><?= __('Information') ?></a>
	</div>
	<div class="account-link">
		<a href="/resource"><?= __('Resources') ?></a>
	</div>
</div>