<?php
    $galleryData = 
        '[
            {
            "title": "Kitchen 1",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam finibus elit lacus, sed consectetur enim euismod a. Nullam eget finibus nisi, at rhoncus massa. Vestibulum suscipit tortor et neque tempor, sit amet blandit nisl facilisis. Quisque orci nisi, varius a mattis non, auctor vel elit. Duis vel accumsan ipsum. Etiam dapibus, tellus nec accumsan vestibulum, nisi nulla rutrum mi, et vulputate dui quam at augue. Donec mollis faucibus volutpat. Cras erat elit, tempus aliquam semper fermentum, molestie quis lacus. Nulla efficitur odio vel congue lobortis. Cras leo nunc, condimentum sed diam eu, pellentesque aliquet dui. Sed lectus quam, rhoncus nec magna sit amet, cursus commodo mauris. Aliquam maximus eu magna in volutpat.",
            "category": "Kitchen",
            "sp": 0
            },
            {
            "title": "Door 1",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Quisque venenatis lorem vestibulum, interdum dolor id, dictum lorem. Cras pharetra quam vitae augue pulvinar, in varius nisi ultricies. Morbi at eros quis mauris molestie commodo non sed sapien. Ut sed luctus lacus. Nulla bibendum feugiat sem tempor venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In vehicula ante velit, eu pharetra mi euismod sit amet.",
            "category": "Door",
            "sp": 0
            },
            {
            "title": "Cabinet 1",
            "img_thumb": "https://dummyimage.com/800x500/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Etiam sed massa in dolor dictum sodales. Nam dapibus velit sed orci ultrices elementum. Praesent quis sagittis est, lobortis dignissim dui. Nulla convallis arcu non lacinia tristique. Proin pulvinar mauris vitae mi fringilla condimentum. Nullam sed quam rutrum, convallis quam eu, rutrum sapien. Nullam viverra elementum odio sit amet auctor. Aliquam erat volutpat. Nullam rhoncus condimentum leo id feugiat. Praesent et sem augue. Donec aliquet enim odio, at tempor nisi tincidunt id. In hac habitasse platea dictumst.",
            "category": "Cabinet",
            "sp": 1
            },
            {
            "title": "Kitchen 2",
            "img_thumb": "https://dummyimage.com/800x500/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Phasellus luctus venenatis sem, ut ultrices ante molestie ac. Nam quis neque sit amet dolor vestibulum mattis eu at arcu. Cras aliquam, ipsum a hendrerit suscipit, risus mauris vestibulum lorem, a scelerisque massa quam a nisl. Ut sit amet porta lorem. Mauris diam felis, ultricies ut quam at, gravida lacinia erat. Mauris a sem in justo ornare blandit at sit amet tellus. Praesent eu ornare nibh, vel elementum leo. Cras convallis dui ac erat mollis tristique. Maecenas suscipit purus sit amet tortor laoreet, id placerat dui semper. Vestibulum scelerisque elit elit, quis eleifend justo pharetra id. Quisque commodo sodales nunc ut interdum. Vivamus luctus erat finibus aliquet dictum.",
            "category": "Kitchen",
            "sp": 1
            },
            {
            "title": "Door 2",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Phasellus pretium vehicula porta. Proin efficitur finibus mi, eu finibus est sagittis eu. Mauris et auctor mi. Ut in aliquet nunc. Etiam eget interdum metus, nec facilisis odio. Proin tincidunt et sapien rutrum dignissim. Nullam ut tortor sollicitudin sem semper pellentesque at gravida metus. Suspendisse vel vestibulum velit.",
            "category": "Door",
            "sp": 0
            },
            {
            "title": "Cabinet 2",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam finibus elit lacus, sed consectetur enim euismod a. Nullam eget finibus nisi, at rhoncus massa. Vestibulum suscipit tortor et neque tempor, sit amet blandit nisl facilisis. Quisque orci nisi, varius a mattis non, auctor vel elit. Duis vel accumsan ipsum. Etiam dapibus, tellus nec accumsan vestibulum, nisi nulla rutrum mi, et vulputate dui quam at augue. Donec mollis faucibus volutpat. Cras erat elit, tempus aliquam semper fermentum, molestie quis lacus. Nulla efficitur odio vel congue lobortis. Cras leo nunc, condimentum sed diam eu, pellentesque aliquet dui. Sed lectus quam, rhoncus nec magna sit amet, cursus commodo mauris. Aliquam maximus eu magna in volutpat.",
            "category": "Cabinet",
            "sp": 0
            },
            {
            "title": "Kitchen 3",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Quisque venenatis lorem vestibulum, interdum dolor id, dictum lorem. Cras pharetra quam vitae augue pulvinar, in varius nisi ultricies. Morbi at eros quis mauris molestie commodo non sed sapien. Ut sed luctus lacus. Nulla bibendum feugiat sem tempor venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In vehicula ante velit, eu pharetra mi euismod sit amet.",
            "category": "Kitchen",
            "sp": 0
            },
            {
            "title": "Door 3",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Etiam sed massa in dolor dictum sodales. Nam dapibus velit sed orci ultrices elementum. Praesent quis sagittis est, lobortis dignissim dui. Nulla convallis arcu non lacinia tristique. Proin pulvinar mauris vitae mi fringilla condimentum. Nullam sed quam rutrum, convallis quam eu, rutrum sapien. Nullam viverra elementum odio sit amet auctor. Aliquam erat volutpat. Nullam rhoncus condimentum leo id feugiat. Praesent et sem augue. Donec aliquet enim odio, at tempor nisi tincidunt id. In hac habitasse platea dictumst.",
            "category": "Door",
            "sp": 0
            },
            {
            "title": "Cabinet 3",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Phasellus luctus venenatis sem, ut ultrices ante molestie ac. Nam quis neque sit amet dolor vestibulum mattis eu at arcu. Cras aliquam, ipsum a hendrerit suscipit, risus mauris vestibulum lorem, a scelerisque massa quam a nisl. Ut sit amet porta lorem. Mauris diam felis, ultricies ut quam at, gravida lacinia erat. Mauris a sem in justo ornare blandit at sit amet tellus. Praesent eu ornare nibh, vel elementum leo. Cras convallis dui ac erat mollis tristique. Maecenas suscipit purus sit amet tortor laoreet, id placerat dui semper. Vestibulum scelerisque elit elit, quis eleifend justo pharetra id. Quisque commodo sodales nunc ut interdum. Vivamus luctus erat finibus aliquet dictum.",
            "category": "Cabinet",
            "sp": 0
            },
            {
            "title": "Kitchen 4",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Phasellus pretium vehicula porta. Proin efficitur finibus mi, eu finibus est sagittis eu. Mauris et auctor mi. Ut in aliquet nunc. Etiam eget interdum metus, nec facilisis odio. Proin tincidunt et sapien rutrum dignissim. Nullam ut tortor sollicitudin sem semper pellentesque at gravida metus. Suspendisse vel vestibulum velit.",
            "category": "Kitchen",
            "sp": 0
            },
            {
            "title": "Door 4",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam finibus elit lacus, sed consectetur enim euismod a. Nullam eget finibus nisi, at rhoncus massa. Vestibulum suscipit tortor et neque tempor, sit amet blandit nisl facilisis. Quisque orci nisi, varius a mattis non, auctor vel elit. Duis vel accumsan ipsum. Etiam dapibus, tellus nec accumsan vestibulum, nisi nulla rutrum mi, et vulputate dui quam at augue. Donec mollis faucibus volutpat. Cras erat elit, tempus aliquam semper fermentum, molestie quis lacus. Nulla efficitur odio vel congue lobortis. Cras leo nunc, condimentum sed diam eu, pellentesque aliquet dui. Sed lectus quam, rhoncus nec magna sit amet, cursus commodo mauris. Aliquam maximus eu magna in volutpat.",
            "category": "Door",
            "sp": 0
            },
            {
            "title": "Cabinet 4",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Quisque venenatis lorem vestibulum, interdum dolor id, dictum lorem. Cras pharetra quam vitae augue pulvinar, in varius nisi ultricies. Morbi at eros quis mauris molestie commodo non sed sapien. Ut sed luctus lacus. Nulla bibendum feugiat sem tempor venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In vehicula ante velit, eu pharetra mi euismod sit amet.",
            "category": "Cabinet",
            "sp": 0
            },
            {
            "title": "Kitchen 5",
            "img_thumb": "https://dummyimage.com/800x500/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Etiam sed massa in dolor dictum sodales. Nam dapibus velit sed orci ultrices elementum. Praesent quis sagittis est, lobortis dignissim dui. Nulla convallis arcu non lacinia tristique. Proin pulvinar mauris vitae mi fringilla condimentum. Nullam sed quam rutrum, convallis quam eu, rutrum sapien. Nullam viverra elementum odio sit amet auctor. Aliquam erat volutpat. Nullam rhoncus condimentum leo id feugiat. Praesent et sem augue. Donec aliquet enim odio, at tempor nisi tincidunt id. In hac habitasse platea dictumst.",
            "category": "Kitchen",
            "sp": 1
            },
            {
            "title": "Door 5",
            "img_thumb": "https://dummyimage.com/800x500/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Phasellus luctus venenatis sem, ut ultrices ante molestie ac. Nam quis neque sit amet dolor vestibulum mattis eu at arcu. Cras aliquam, ipsum a hendrerit suscipit, risus mauris vestibulum lorem, a scelerisque massa quam a nisl. Ut sit amet porta lorem. Mauris diam felis, ultricies ut quam at, gravida lacinia erat. Mauris a sem in justo ornare blandit at sit amet tellus. Praesent eu ornare nibh, vel elementum leo. Cras convallis dui ac erat mollis tristique. Maecenas suscipit purus sit amet tortor laoreet, id placerat dui semper. Vestibulum scelerisque elit elit, quis eleifend justo pharetra id. Quisque commodo sodales nunc ut interdum. Vivamus luctus erat finibus aliquet dictum.",
            "category": "Door",
            "sp": 1
            },
            {
            "title": "Cabinet 5",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Phasellus pretium vehicula porta. Proin efficitur finibus mi, eu finibus est sagittis eu. Mauris et auctor mi. Ut in aliquet nunc. Etiam eget interdum metus, nec facilisis odio. Proin tincidunt et sapien rutrum dignissim. Nullam ut tortor sollicitudin sem semper pellentesque at gravida metus. Suspendisse vel vestibulum velit.",
            "category": "Cabinet",
            "sp": 0
            },
            {
            "title": "Kitchen 6",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam finibus elit lacus, sed consectetur enim euismod a. Nullam eget finibus nisi, at rhoncus massa. Vestibulum suscipit tortor et neque tempor, sit amet blandit nisl facilisis. Quisque orci nisi, varius a mattis non, auctor vel elit. Duis vel accumsan ipsum. Etiam dapibus, tellus nec accumsan vestibulum, nisi nulla rutrum mi, et vulputate dui quam at augue. Donec mollis faucibus volutpat. Cras erat elit, tempus aliquam semper fermentum, molestie quis lacus. Nulla efficitur odio vel congue lobortis. Cras leo nunc, condimentum sed diam eu, pellentesque aliquet dui. Sed lectus quam, rhoncus nec magna sit amet, cursus commodo mauris. Aliquam maximus eu magna in volutpat.",
            "category": "Kitchen",
            "sp": 0
            },
            {
            "title": "Door 6",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Quisque venenatis lorem vestibulum, interdum dolor id, dictum lorem. Cras pharetra quam vitae augue pulvinar, in varius nisi ultricies. Morbi at eros quis mauris molestie commodo non sed sapien. Ut sed luctus lacus. Nulla bibendum feugiat sem tempor venenatis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In vehicula ante velit, eu pharetra mi euismod sit amet.",
            "category": "Door",
            "sp": 0
            },
            {
            "title": "Cabinet 6",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Etiam sed massa in dolor dictum sodales. Nam dapibus velit sed orci ultrices elementum. Praesent quis sagittis est, lobortis dignissim dui. Nulla convallis arcu non lacinia tristique. Proin pulvinar mauris vitae mi fringilla condimentum. Nullam sed quam rutrum, convallis quam eu, rutrum sapien. Nullam viverra elementum odio sit amet auctor. Aliquam erat volutpat. Nullam rhoncus condimentum leo id feugiat. Praesent et sem augue. Donec aliquet enim odio, at tempor nisi tincidunt id. In hac habitasse platea dictumst.",
            "category": "Cabinet",
            "sp": 0
            },
            {
            "title": "Kitchen 7",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Phasellus luctus venenatis sem, ut ultrices ante molestie ac. Nam quis neque sit amet dolor vestibulum mattis eu at arcu. Cras aliquam, ipsum a hendrerit suscipit, risus mauris vestibulum lorem, a scelerisque massa quam a nisl. Ut sit amet porta lorem. Mauris diam felis, ultricies ut quam at, gravida lacinia erat. Mauris a sem in justo ornare blandit at sit amet tellus. Praesent eu ornare nibh, vel elementum leo. Cras convallis dui ac erat mollis tristique. Maecenas suscipit purus sit amet tortor laoreet, id placerat dui semper. Vestibulum scelerisque elit elit, quis eleifend justo pharetra id. Quisque commodo sodales nunc ut interdum. Vivamus luctus erat finibus aliquet dictum.",
            "category": "Kitchen",
            "sp": 0
            },
            {
            "title": "Door 7",
            "img_thumb": "https://dummyimage.com/400/09284c/fff",
            "img_full": "https://dummyimage.com/2000x1000/09284c/fff",
            "desc": "Phasellus pretium vehicula porta. Proin efficitur finibus mi, eu finibus est sagittis eu. Mauris et auctor mi. Ut in aliquet nunc. Etiam eget interdum metus, nec facilisis odio. Proin tincidunt et sapien rutrum dignissim. Nullam ut tortor sollicitudin sem semper pellentesque at gravida metus. Suspendisse vel vestibulum velit.",
            "category": "Door",
            "sp": 0
            }
        ]';
    $galleryArray = json_decode($galleryData, true);
    // var_dump($galleryArray);
    // die();
    
?>

<div class="gallery-intro-desc max-width">
    <div class="gallery-switch">
        <div class="switch-item"><a href="#" class="active">Kitchens</a></div>
        <div class="switch-item"><a href="#">Vanities</a></div>
    </div>
    <div class="intro-desc">
        <article>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia.
        </article>
    </div>
</div>
<div class="gallery-grid-container ">
        <div class="gallery-items">
            <?php foreach($galleryArray as $key => $content):?>
                <?php
                    $title = $content['title'];
                    $thumb = $content['img_thumb'];
                    $imgFull = $content['img_full'];
                    $desc = $content['desc'];
                    $category = $content['category'];
                    $sp = $content['sp'];
                    $isSp = false;
                    if($sp == '1'){
                        $isSp = true;
                    }else{
                        $isSp = false;
                    }
                ?>
                <div class="gallery-item grid-item <?php if($isSp):?>sp-grid-item<?php endif ?>">
                    
                    <div class="g-item">
                        <a href="<?= $imgFull?>" class="popUp" title="<?= $title ?>" data-fancybox="gallery">
                        <div class="zoom_btn">
                            <img  src="<?php echo $block->getViewFileUrl('images/icons/Zoom_In.svg'); ?>"  />
                        </div>
                            <img class="gallery-thumb" src="<?= $thumb?>" alt="<?= $title ?>">
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="popup-content" style="display: none;">
            <?php foreach($galleryArray as $key => $content):?>
                <?php
                    $title = $content['title'];
                    $thumb = $content['img_thumb'];
                    $imgFull = $content['img_full'];
                    $desc = $content['desc'];
                    $category = $content['category'];
                    $sp = $content['sp'];
                    $isSp = false;
                    if($sp == '1'){
                        $isSp = true;
                    }else{
                        $isSp = false;
                    }
                ?>
                <div class="popup-item">
                    <div class="popup-item-container">
                    <figure>
                        <img src="<?= $imgFull ?>" alt="<?= $title ?>">
                    </figure>
                    <div class="popup-title">
                        <span><?= $title ?></span>
                    </div>
                    <div class="popup-desc">
                    <article><?= $desc ?></article>
                    </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
</div>

<script type="text/javascript">
	require(['jquery','fancybox'], function($){
		$(document).ready(function() {
            $('.popUp').each(function(key,item){
                $(this).attr('href', `#grid-item-${key}`) 
            })
            $('.popup-item').each(function(key,item){
                this.id = `grid-item-${key}`
            })
			// $('.gallery-items').magnificPopup({
            //     delegate: '.popUp',
            //     type: 'image',
            //     closeOnContentClick: false,
            //     closeBtnInside: false,
            //     mainClass: 'mfp-with-zoom mfp-img-mobile',
            //     image: {
            //         verticalFit: true,
            //         titleSrc: function(item) {
            //             return item.el.attr('title');
            //         }
            //     },
            //     gallery: {
            //         enabled: true
            //     },
            //     zoom: {
            //         enabled: true,
            //         duration: 300, // don't foget to change the duration also in CSS
            //         opener: function(element) {
            //             return element.find('img');
            //         }
            //     }
            // })
            $('.popUp').fancybox({
                arrows: true,
                keyboard: true,
                infobar: true,
                smallBtn: 'auto',
            });
		});
	});
</script>


